apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buggy
  template:
    metadata:
      labels:
        app: buggy
    spec:
      containers:
      - name: buggy
        image: 619141221545.dkr.ecr.eu-west-1.amazonaws.com/expleoecr1-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: buggy
    k8s-app: buggy
  name: buggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: buggy